
version: "3.8"
services:
  redpanda:
    image: redpandadata/redpanda:v24.2.10
    command:
      - redpanda start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
      - --pandaproxy-addr=0.0.0.0:8082
      - --advertise-pandaproxy-addr=localhost:8082
    ports: [ "19092:19092", "8082:8082" ]
  redpanda-console:
    image: redpandadata/console:v2.7.2
    depends_on: [ redpanda ]
    environment:
      KAFKA_BROKERS: "redpanda:9092"
    ports: [ "8081:8080" ]

  localstack:
    image: localstack/localstack:3.7
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
